### ISSUE TITLE
Generalize Geolexica backend

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/geolexica-server#1]
We need to generalize the Geolexica backend to support:

* Git/YAML backed concepts datastore
* Ontologies (RDF TTL, SKOS JSON-LD) (see `_layouts/` output)

Then we need to refactor these repos to use this new gem:

* https://github.com/ISO-TC211/geolexica.org
* https://github.com/geolexica/osgeo.geolexica.org

**Comment by skalee** [comment]
- [ ] Push the contents of geolexica.org repo to this very repo (as it is a working geolexica site).
- [ ] Extract Geolexica plugin.
- [ ] Package Geolexica plugin as a gem (discussion on gem name in #4).
- [ ] Apply Geolexica plugin to ISO-TC211 site.
- [ ] Apply Geolexica plugin to Osgeo site.

**Comment by skalee** [comment]
I suppose this can be marked as fixed now. For umbrella gem, see #46.
