### ISSUE TITLE
Remove wording of "Use at your own risk." for aberrant sourced term, reword "definitive" to "normative"

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/geolexica-server#101]
Remove wording of "Use at your own risk." for aberrant sourced term, reword "definitive" to "normative".

<img width="968" alt="Screen Shot 2020-06-10 at 8 09 36 PM" src="https://user-images.githubusercontent.com/11865/84267771-2e924b80-ab59-11ea-8423-6bec0a4f4b72.png">

**Comment by skalee** [comment]
And it has been released yesterday.
