### ISSUE TITLE
Mathematical formulae should be rendered with MathJax

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#109]
We want to render MathML with [MathJax](https://www.mathjax.org/).

Although modern browsers are capable of rendering MathML themselves, this support is sometimes buggy or feature-incomplete. See following example taken from IEV concept 103-01-02 (mind parenthesis and both horizontal and vertical positioning):

| Firefox | ![](https://user-images.githubusercontent.com/154287/85949876-90282780-b959-11ea-95e3-bb3987780e25.png) |
|-|-|
| Safari | ![](https://user-images.githubusercontent.com/154287/85949878-91595480-b959-11ea-854b-f1c539e3d9b0.png) |

For reference, actual HTML and MathML:

```html
<p>An example of a functional of the function <math><mi>f</mi></math>(<math><mi>t</mi></math>) is <math><msubsup><mo>∫</mo><msub><mi>t</mi><mn>2</mn></msub><msub><mi>t</mi><mn>1</mn></msub></msubsup><mi>f</mi><mfenced open="(" close=")"><mi>t</mi></mfenced><mi>d</mi><mi>t</mi></math>.</p>
```

### TODO

- [ ] Add MathJax support to Jekyll-Geolexica (#110).
- [ ] Enable MathJax on IEV site.

**Comment by skalee** [comment]
For reference, thanks to MathJax now it renders as follows:

| Firefox | ![Zrzut ekranu 2020-06-28 o 16 29 59](https://user-images.githubusercontent.com/154287/85951077-1a27be80-b961-11ea-9372-a5a0be4fcea7.png) |
|-|-|
| Safari |![Zrzut ekranu 2020-06-28 o 16 30 13](https://user-images.githubusercontent.com/154287/85951079-1ac05500-b961-11ea-84fc-57fb728dde96.png) |

**Comment by ronaldtse** [comment]
Thanks @skalee !
