### ISSUE TITLE
In search filter, darken the rows that are not active

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/geolexica-server#134]
From @ReesePlews :
Superceded/retired terms should be highlighted in dark gray to indicate it is no longer active.

<img width="1193" alt="Screen Shot 2020-06-18 at 10 34 54 AM" src="https://user-images.githubusercontent.com/11865/84975398-dc07ef00-b157-11ea-87ac-6faef06ac088.png">

**Comment by skalee** [comment]
Is it a problem with transferring requests like this one to geolexica-server repository? I keep plenty of other search-related requests here.

**Comment by ronaldtse** [comment]
@skalee no problem, up to you on what is appropriate in what repository.
