### ISSUE TITLE
Update Jekyll to 4.2

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#152]
Jekyll 4.2 has been released. Got to ensure compatibility and bump version constraints.

**Comment by ronaldtse** [comment]
There’s an incompatibility with Jekyll-data, which is not resolved yet there, seems like.

**Comment by skalee** [comment]
Actually, they fixed it. But it hasn't been released yet. https://github.com/ashmaroli/jekyll-data/issues/39#issuecomment-760959155

**Comment by skalee** [comment]
This particular gem does not depend on jekyll-data. Closing in favour of https://github.com/geolexica/geolexica-site/issues/1.
