### ISSUE TITLE
Concept links with URNs not showing properly

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/geolexica-server#182]
https://isotc204.geolexica.org/concepts/3.5.9.3/

<img width="781" alt="Screen Shot 2022-08-11 at 9 46 53 AM" src="https://user-images.githubusercontent.com/11865/184051374-48165177-d89c-47d8-9460-8c76bf4a9e71.png">

**Comment by ronaldtse** [comment]
This is probably since we haven't bumped versions yet.

**Comment by HassanAkbar** [comment]
@ronaldtse Verified this is working now and the issue can be closed.

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar !

**Comment by ronaldtse** [comment]
Confirmed. <img width="813" alt="Screen Shot 2022-08-18 at 3 53 43 PM" src="https://user-images.githubusercontent.com/11865/185340893-393ee7ac-5330-41c2-879e-1aed98c49f4b.png">
