### ISSUE TITLE
Make configurable the generation of machine-readable outputs

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/geolexica-server#38]
We now provide JSON, RDF JSON-LD, RDF TTL and TBX.

The user should be able to "configure" which ones they want to be created by the server, or none, in their `_config.yml`?

Or maybe this is bad for consistency and manageability (of us)?

**Comment by skalee** [comment]
We definitely want it. I thought that I've created an issue about that, but apparently I haven't.

Actually, lack of this configuration setting is the only reason why OsGeo still has its own branch of this repository.

**Comment by skalee** [comment]
Fixed in #45.
