### ISSUE TITLE
New designation attributes should be shown on concept page

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/geolexica-server#40]
- [ ] geographicalArea
- [ ] usageInfo
- [ ] gender
- [ ] plurality
- [ ] partOfSpeech

**Comment by ronaldtse** [comment]
As noted in https://github.com/glossarist/iev-demo-site/issues/16 , ISO 3166 code in `geographicalArea` must be in capital cases.

**Comment by HassanAkbar** [comment]
@ronaldtse does this view looks good or do I need to change anything here ?

<img width="1440" alt="Screenshot 2022-07-29 at 4 02 46 PM" src="https://user-images.githubusercontent.com/5301572/181746299-961fa156-19f0-46b1-ba41-fa6a2c499ed9.png">

**Comment by ronaldtse** [comment]
@HassanAkbar we need to update the representations according to the formats defined in ISO 10241-1 and the Electropedia. I have inserted the examples here:.

<img width="639" alt="Screen Shot 2022-07-30 at 11 46 29 AM" src="https://user-images.githubusercontent.com/11865/181867236-b9476a99-d933-4fad-b8b6-2bb9cf772b66.png">

Usage info. Displayed next to the term in angular brackets. `my term <{usage info>`
https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=103-02-03
<img width="719" alt="Screen Shot 2022-07-30 at 11 45 50 AM" src="https://user-images.githubusercontent.com/11865/181867216-f5487c10-3e63-45e9-adcb-138a51f2d5c2.png">

Domain. Displayed in front of the definition in angular brackets.
<img width="658" alt="Screen Shot 2022-07-30 at 11 47 00 AM" src="https://user-images.githubusercontent.com/11865/181867257-fa5e129e-dbe0-448a-8707-871600dcd895.png">

Grammatical gender:
<img width="649" alt="Screen Shot 2022-07-30 at 11 48 28 AM" src="https://user-images.githubusercontent.com/11865/181867314-abfbccd5-2842-4e5d-81df-8107f581b965.png">
<img width="642" alt="Screen Shot 2022-07-30 at 11 51 24 AM" src="https://user-images.githubusercontent.com/11865/181867399-87eff58d-4725-421c-98e7-995360c08e02.png">


Language. Only for non-English/French (i.e. not ISO 639 `en` and `fr`) and non-Latin script (i.e. not ISO 15924 `Latn` script).
<img width="636" alt="Screen Shot 2022-07-30 at 11 49 49 AM" src="https://user-images.githubusercontent.com/11865/181867356-97646fb2-c8e3-42f5-beeb-e87b231d9f21.png">

Geographic area:
<img width="887" alt="Screen Shot 2022-07-30 at 11 36 46 AM" src="https://user-images.githubusercontent.com/11865/181866951-53a23ec6-53ef-4370-9050-2d6260664bad.png">

Parts of speech.
<img width="653" alt="Screen Shot 2022-07-30 at 11 47 53 AM" src="https://user-images.githubusercontent.com/11865/181867292-1675409b-2277-4209-83a0-59463350ea21.png">

NOTE: We should document this in the README.
