### ISSUE TITLE
Language codes should always be in lower-case

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/geolexica-server#41]
> Language codes (alpha-2 or alpha-3) shall be lower case letters for conformity with ISO 639: http://www.loc.gov/standards/iso639-2/php/code_list.php.
> It is the country codes that are capital letters as per ISO 3166.

<img width="1101" alt="Screen Shot 2020-04-14 at 11 48 48 PM" src="https://user-images.githubusercontent.com/11865/79245285-7de63380-7eaa-11ea-9d9b-102a4308cb21.png">

We should not capitalize the language codes on the Concept page.

https://github.com/glossarist/iev-demo-site/issues/16

**Comment by skalee** [comment]
This may be a purely aesthetics question… What about fields like "term id", "source"? Should they be lowercased as well, or contrary?

![Zrzut ekranu 2020-04-15 o 23 44 57](https://user-images.githubusercontent.com/154287/79392186-44c5c600-7f73-11ea-91f7-55a6d959063e.png)

**Comment by ronaldtse** [comment]
SOURCE has to be in caps. "TERM ID" doesn't matter.
