### ISSUE TITLE
Language tags used in RDF output should follow BCP47

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#51]
[IANALSR]: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

**SUMMARY: Can we use ISO 639-2 codes (three characters long ones) when tagging strings in RDF output?**

Right now there is some mess, and we should to clean it up.

----

This issue has been created as a result of comments by @ronaldtse right after merging #48 in:

> According to BCP47, ISO 639-2 codes are directly supported. See 2.2.1. (…)
> Please use 639-2 language tags because it is necessary for TC 211 languages.

I understand that it is agreed that language tags in RDF output should follow BCP47, however there is some misunderstanding on what BCP47 actually requires.

### References to RDF language specifications

NOTE: This section explains why BCP47 is required. There is no apparent misunderstanding on this topic. It has been written for clarity. 

RFC for RDF 1.1 defines language tags as follows:

> if and only if the datatype IRI is http://www.w3.org/1999/02/22-rdf-syntax-ns#langString, a non-empty language tag as defined by [BCP47]. The language tag MUST be well-formed according to section 2.2.9 of [BCP47].
>
> ---- _https://www.w3.org/TR/rdf11-concepts/#dfn-language-tagged-string_

This also applies for Turtle, which directly points to RDF 1.1 spec (see: https://www.w3.org/TR/turtle/#turtle-literals).

Similarly, JSON-LD spec says that:

> The keys of a language map MUST be strings representing [BCP47] language tags, the keyword @\none, or a term which expands to @\none [_skipped_].
>
> ---- _https://www.w3.org/TR/json-ld/#language-maps, shortened for clarity_

### What BCP47 actually says:

> 2.2.1.  Primary Language Subtag
> 
> [_skipped_]
> 
> The following rules apply to the primary language subtag:
> 
>    1.  Two-character primary language subtags were defined in the IANA
>        registry according to the assignments found in the standard "ISO
>        639-1:2002, Codes for the representation of names of languages --
>        Part 1: Alpha-2 code" [ISO639-1], or using assignments
>        subsequently made by the ISO 639-1 registration authority (RA) or
>        governing standardization bodies.
> 
>    2.  Three-character primary language subtags in the IANA registry
>        were defined according to the assignments found in one of these
>        additional ISO 639 parts or assignments subsequently made by the
>        relevant ISO 639 registration authorities or governing
>        standardization bodies:
> 
>        A.  "ISO 639-2:1998 - Codes for the representation of names of
>            languages -- Part 2: Alpha-3 code - edition 1" [ISO639-2]
> 
>        B.  "ISO 639-3:2007 - Codes for the representation of names of
>            languages -- Part 3: Alpha-3 code for comprehensive coverage
>            of languages" [ISO639-3]
> 
>        C.  "ISO 639-5:2008 - Codes for the representation of names of
>            languages -- Part 5: Alpha-3 code for language families and
>            groups" [ISO639-5]
> 
>    3. [_skipped_]
>    4. [_skipped_]
>    5. [_skipped_]
> 
>    6.  Other values MUST NOT be assigned to the primary subtag except by
>        revision or update of this document.
> 
> ---- _https://tools.ietf.org/html/bcp47#section-2.2.1, shortened for clarity_

In my understanding, point 2. does not imply that every language code listed in ISO 639-2:1998 is valid for use in language tags. The only source of valid language subtags is [IANA Language Subtags Registry][IANALSR], which includes some of ISO 639-2:1998 ones, but not all of them. And in fact, BCP47 says further:

>    When languages have both an ISO 639-1 two-character code and a three-
>    character code (assigned by ISO 639-2, ISO 639-3, or ISO 639-5), only
>    the ISO 639-1 two-character code is defined in the IANA registry.
> 
> ---- _https://tools.ietf.org/html/bcp47#section-2.2.1_

For example, "deu", "eng", and "pol" are not listed in the IANA registry, as these languages are identified by "de", "en", and "pl", respectively.

----

The conclusion is, IMO we should stick to BCP47 in all RDF output. We can continue to use ISO 639-2 three letter codes on human-readable pages.

I am not sure of requirements for ISO-TBX-TBT format, but I have a suspicion that it also relies on BCP47.

----

cc @ronaldtse

**Comment by skalee** [comment]
Also https://github.com/geolexica/geolexica-server/issues/2#issuecomment-613174921 by @ronaldtse (bold emphasis mine):

> @skalee regarding 2-char vs 3-char language codes (2.), the answer is this:
> 
> https://listserv.loc.gov/cgi-bin/wa?A2=ind1407&L=BIBFRAME&P=853
> 
> > In BCP 47 (aka RFC 5646) it is not a question of “preference” in terms of which language code to use. It has been a long-standing policy in the previous RFC’s concerning language coding (RFC4646 and its predecessors) that if using that specification you use the 2-character language code from ISO 639-1 if there is one as the primary subtag. If there is not you use the 3-character one from ISO 639-2. The ISO 639-1 list has essentially been frozen for many years and includes far fewer language codes (because obviously there are fewer combinations when using 2 characters) than ISO 639-2 (or 3).
> >
> > Rebecca
> > (former chair of the ISO 639 Joint Advisory Committee)
> 
> **Since RDF refers to BCP47 in its "language tag", we should use a 2-char ISO 639-1 code if it exists, otherwise a 3-char ISO 639-2 code**.

**Comment by ronaldtse** [comment]
@skalee Thanks for reminding 😉 

In ISO-TBX-TBT the lang tag is this: https://www.iso.org/schema/nisosts/v0.2/doc/tbx/index.html

**Comment by skalee** [comment]
Yes, sorry for this screed. I was bit confused myself, did some research, and wanted to leave some trace of it in case we get back to it again. Also in case TC 211 doesn't like IANA and insists on pure ISO standards ;)

Regarding ISO-TBX-TBT, I understand that means it is BCP47 as well.

**Comment by skalee** [comment]
Both Turtle and JSON-LD outputs have proper tags for some time. ISO-TBX-TBT is not implemented in this reposiotry yet, so there's no bug there. Closing then.

**Comment by ronaldtse** [comment]
@skalee can you help add ISO-TBT-TBX to all instanceS? Thanks!

**Comment by skalee** [comment]
@ronaldtse Sure (as of #36) but I don't consider it an urgent thing.

From my POV, a huge issue (almost a blocker) in last weeks was maintainability, and this is what I was fixing recently. Then RDF output, which still needs to be fixed. And then TBX.

**Comment by ronaldtse** [comment]
Yup, agree.
